# Generated by Django 3.0 on 2021-02-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_event_membership_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end_time',
        ),
    ]
