# Generated by Django 3.0 on 2021-02-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20210205_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reward',
        ),
    ]
