# Generated by Django 3.0 on 2021-02-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_event_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='reward',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
